# Generated by Django 5.2 on 2025-04-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_sliderhomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('little_text', models.TextField(max_length=100)),
                ('img', models.ImageField(upload_to='service')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'Сервис',
            },
        ),
    ]
