# Generated by Django 5.1.6 on 2025-05-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_servicehomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='payMethod')),
            ],
            options={
                'verbose_name': 'способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
    ]
